ipv6 support
php-amqplib/php-amqplib pull request #1145
Opened 2023-12-01 22:19 UTC by InnoT20

**Description of Changes**
This pull request adds support for IPv6 for socket connection

**Changes Made**
- Added IPv6 support for working with sockets.
- Implemented domain DNS checking to handle cases where the domain leads to an IPv6 address.

2023-12-02 10:49 UTC, ramunasd requested changes

2023-12-02 10:49 UTC, ramunasd commented on PhpAmqpLib/Wire/IO/SocketIO.php
> +        $this->isIpv6 = $this->isIpv6();
We don't need to keep this variable as class property if it is being used in only one place and only once.

2023-12-02 10:49 UTC, ramunasd commented on PhpAmqpLib/Wire/IO/SocketIO.php
> +        $this->sock = socket_create(!$this->isIpv6 ? AF_INET : AF_INET6, SOCK_STREAM, SOL_TCP);
Call method `isIpv6()` instead of var.

2023-12-02 10:49 UTC, ramunasd commented on tests/Unit/Wire/IO/StreamIOTest.php
> +        return $streamIO;
There is no need to return anything from test method. Just make sure all assertions are implemented.

2023-12-02 10:51 UTC, ramunasd commented
Thanks for improvement!
I have question regarding stream implementation. Does it support ipv6 addresses without any modifications?

2023-12-02 11:36 UTC, InnoT20 commented
> Thanks for improvement! I have question regarding stream implementation. Does it support ipv6 addresses without any modifications?

The stream implementation supports IPv6 addresses without requiring any additional modifications. 
I've locally verified this on PHP version 8.1, confirming that the stream works seamlessly with IPv6 addresses.

2023-12-04 10:59 UTC, ramunasd approved these changes

2023-12-04 14:15 UTC, merged